# config/services.yaml
parameters:
    app.jwtsecret: '%env(JWT_SECRET)%'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    csv_directory: '%kernel.project_dir%/assets/data/csv'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $photosDirectory: '%photos_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\CheckActiveUserListener:
        tags:
            - { name: kernel.event_listener, event: security.authentication.success }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Add more service definitions here if needed
